package com.nanosolution.aecontrol.model;
// Generated 6/11/2016 08:20:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="aecontrol"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String apellidos;
     private String identificacion;
     private String clave;
     private char estado;
     private int idRol;

    public Usuario() {
    }

	
    public Usuario(String nombre, String identificacion, String clave, char estado, int idRol) {
        this.nombre = nombre;
        this.identificacion = identificacion;
        this.clave = clave;
        this.estado = estado;
        this.idRol = idRol;
    }
    public Usuario(String nombre, String apellidos, String identificacion, String clave, char estado, int idRol) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.identificacion = identificacion;
       this.clave = clave;
       this.estado = estado;
       this.idRol = idRol;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidos", length=200)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="identificacion", nullable=false, length=30)
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    
    @Column(name="clave", nullable=false, length=30)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }

    
    @Column(name="id_rol", nullable=false)
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }




}


